version: "3.8"

services:
  backend:
    image: esojas/hishiro-ticketing-system-backend:latest
    restart: always
    environment:
      PORT: ${PORT}
      NODE_ENV: ${NODE_ENV}
      MONGO_URI: ${MONGO_URI}
      JWT_SECRET: ${JWT_SECRET}
      FIREBASE_SERVICE_ACCOUNT: ${FIREBASE_SERVICE_ACCOUNT}
    ports:
      - "3032:3032"

  frontend:
    image: esojas/hishiro-ticketing-system-frontend:latest
    restart: always
    depends_on:
      - backend
    environment:
      VITE_API_URL: ${VITE_API_URL}
      VITE_GEMINI_API_KEY: ${VITE_GEMINI_API_KEY}
    ports:
      - "3031:3031"
