version: "3.8"

services:
  backend:
    image: esojas/hishiro-ticketing-system-backend:latest
    restart: always
    environment:
      PORT: ${PORT:-3032}
      NODE_ENV: ${NODE_ENV:-development}
      MONGO_URI: ${MONGO_URI:-mongodb://e2425-wads-l4ccg2:chud6spe@10.25.143.17:27018/e2425-wads-l4ccg2?authSource=e2425-wads-l4ccg2}
      JWT_SECRET: ${JWT_SECRET:-this_is_secret2123}
      FIREBASE_SERVICE_ACCOUNT: ${FIREBASE_SERVICE_ACCOUNT}
    ports:
      - "3032:3032"

  frontend:
    image: esojas/hishiro-ticketing-system-frontend:latest
    restart: always
    depends_on:
      - backend
    environment:
      VITE_API_URL: ${VITE_API_URL:-http://localhost:3032}
      VITE_GEMINI_API_KEY: ${VITE_GEMINI_API_KEY:-AIzaSyDv7xrV4vtbgY-xfAn8dusfbUJ5VOTMGNg}
    ports:
      - "3031:3031"
