version: "3.8"

services:
  backend:
    image: esojas/hishiro-ticketing-system-backend:latest
    restart: always
    environment:
      #Change port to 3032
      PORT: ${PORT}
      NODE_ENV: ${NODE_ENV}
      MONGO_URI: mongodb://e2425-wads-l4ccg2:chud6spe@10.25.143.17:27017/e2425-wads-l4ccg2?authSource=e2425-wads-l4ccg2
      JWT_SECRET: ${JWT_SECRET}
      FIREBASE_SERVICE_ACCOUNT: ${FIREBASE_SERVICE_ACCOUNT}
      GEMINI_API_KEY: ${GEMINI_API_KEY}
    ports:
      - "3032:3032"

  frontend:
  # Dont forget to put correct image
    image: esojas/hishiro-ticketing-system-frontend:latest
    restart: always
    depends_on:
      - backend
    ports:
      - "3031:3031"
