name: Hishiro Ticketing System CI/CD

# Fixed workflow triggers
on:
  push:
    branches:
      - main
    paths-ignore:
      - "README.md"
  pull_request:
    branches:
      - main

jobs:
  continuous-integration:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Backend Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/hishiro-ticketing-system-backend:latest ./server
          docker push ${{ secrets.DOCKER_USERNAME }}/hishiro-ticketing-system-backend:latest

      - name: Build and Push Frontend Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/hishiro-ticketing-system-frontend:latest ./client
          docker push ${{ secrets.DOCKER_USERNAME }}/hishiro-ticketing-system-frontend:latest

  continuous-deployment:
    needs: continuous-integration
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Docker Rootless Environment
        run: |
          echo "Setting up Docker rootless env..."
          echo "export PATH=$HOME/bin:$PATH" >> $GITHUB_ENV
          echo "export DOCKER_HOST=unix://$XDG_RUNTIME_DIR/docker.sock" >> $GITHUB_ENV

      - name: Pull Latest Backend Image
        run: docker pull ${{ secrets.DOCKER_USERNAME }}/hishiro-ticketing-system-backend:latest

      - name: Pull Latest Frontend Image
        run: docker pull ${{ secrets.DOCKER_USERNAME }}/hishiro-ticketing-system-frontend:latest

      - name: Stop and Remove Old Containers
        run: |
          docker compose down || true
          docker system prune -f

      - name: Run New Containers
        run: |
          docker compose up -d
        env:
          PORT: ${{ secrets.PORT }}
          NODE_ENV: ${{ secrets.NODE_ENV }}
          MONGO_URI: ${{ secrets.MONGO_URI }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          VITE_API_URL: ${{ secrets.VITE_API_URL }}
          VITE_GEMINI_API_KEY: ${{ secrets.VITE_GEMINI_API_KEY }}